name: Build Windows EXE - Nuitka

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Download Dependency Walker
        run: |
          Invoke-WebRequest -Uri "http://dependencywalker.com/depends22_x64.zip" -OutFile depends64.zip
          Expand-Archive -Path depends64.zip -DestinationPath "$env:LOCALAPPDATA\Nuitka\Nuitka\Cache\depends\x86_64"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka PySide6

      - name: Build EXE with Nuitka
        run: |
          python -m nuitka `
            --standalone `
            --onefile `
            --enable-plugin=pyside6 `
            --include-qt-plugins=qml `
            --include-data-files=main.qml=main.qml `
            --include-data-files=calc.svg=calc.svg `
            --windows-icon-from-ico=calc.ico `
            --output-filename=calc.exe main.py
        env:
          NUITKA_AUTO_UPDATE_DEPENDENCIES: yes

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: Calc-exe
          path: calc.exe
